const char page_html_begin[] PROGMEM = "<html>\n"
"<head>\n"
"<meta name='viewport' content='width=device-width, initial-scale=1, user-scalable=no'/>\n"
"<meta http-equiv='Cache-Control' content='no-cache, no-store, must-revalidate'>\n"
"<meta http-equiv='Pragma' content='no-cache'>\n"
"<meta http-equiv='Expires' content='0'>\n"
"<meta charset='UTF-8'>\n"
"<title>micro-Trident8266</title>\n"
"<style>\n"
"\n"
"body {background: #8EC2E5;font-family: 'Open Sans', sans-serif;font-weight: 300;}\n"
".c{text-align: center;}\n"
"h1{color: #00137F;}\n"
".divzero {padding: 0}\n"
"div,input{padding:5px;font-size:1em;}\n"
"table{width: 100%;}\n"
"th,td{height: 1.5em;}\n"
"tr {height: 2.7em;}\n"
".tdsmall {height: 10px;}\n"
".td_form {width: 100px;}\n"
".tdzero {padding-right:0px;padding-left:0px;}\n"
"\n"
"select{height: 2em;}\n"
"input{width:95%;} body{text-align: center;font-family:verdana;}\n"
"button{border:0;border-radius:0.3rem;background-color:#0094FF;color:#fff;line-height:2.4rem;font-size:1.2rem;width:100%;}\n"
"button:disabled,button[disabled]{\n"
"  border: 1px solid #999999;\n"
"  background-color: #cccccc;\n"
"  color: #666666;\n"
"}\n"
"\n"
"\n"
".q{float: right;width: 64px;text-align: right;}\n"
".l{background: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAALVBMVEX///8EBwfBwsLw8PAzNjaCg4NTVVUjJiZDRUUUFxdiZGSho6OSk5Pg4eFydHTCjaf3AAAAZElEQVQ4je2NSw7AIAhEBamKn97/uMXEGBvozkWb9C2Zx4xzWykBhFAeYp9gkLyZE0zIMno9n4g19hmdY39scwqVkOXaxph0ZCXQcqxSpgQpONa59wkRDOL93eAXvimwlbPbwwVAegLS1HGfZAAAAABJRU5ErkJggg==') no-repeat left center;background-size: 1em;}\n"
"em{font-size: 14px;text-align: center;display: block;margin-bottom: 50px;}\n"
"em{color: #00137F;font-size: 30px;font-weight: bold;text-align: center; margin: 20px 0 0 0;-webkit-font-smoothing: antialiased;text-shadow: 0px 1px #FFFFFF;}\n"
"\n"
".group {\n"
"  border:dotted 3px rgba(0,0,0,0.25);\n"
"  border-radius:1em;  \n"
"  margin:0;\n"
"  margin:-3px;\n"
"  border-color:gray;\n"
"  min-height:10em;\n"
"  padding:1em;\n"
"  width: 90%;\n"
"}\n"
"#subsetting {font-size: 20px;font-weight: bold;}\n"
"#groupsetting {font-size: 28px;font-weight: bold;}\n"
"#groupbar {font-size: 15px;font-weight: bold;}\n"
"\n"
"input[type=checkbox]\n"
"{\n"
"  /* Double-sized Checkboxes */\n"
"  -ms-transform: scale(2); /* IE */\n"
"  -moz-transform: scale(2); /* FF */\n"
"  -webkit-transform: scale(2); /* Safari and Chrome */\n"
"  -o-transform: scale(2); /* Opera */\n"
"  padding: 10px;\n"
"}\n"
".radio_display_none{\n"
"  display: none;\n"
"}\n"
"input[type=radio] + label, input[type=checkbox] + label {\n"
"  display:inline-block;\n"
"  margin:-2px;\n"
"  padding: 4px 12px;\n"
"  margin-bottom: 0;\n"
"  font-size: 14px;\n"
"  line-height: 20px;\n"
"  color: #333;\n"
"  text-align: center;\n"
"  text-shadow: 0 1px 1px rgba(255,255,255,0.75);\n"
"  vertical-align: middle;\n"
"  cursor: pointer;\n"
"  background-color: #f5f5f5;\n"
"  background-image: -moz-linear-gradient(top,#fff,#e6e6e6);\n"
"  background-image: -webkit-gradient(linear,0 0,0 100%,from(#fff),to(#e6e6e6));\n"
"  background-image: -webkit-linear-gradient(top,#fff,#e6e6e6);\n"
"  background-image: -o-linear-gradient(top,#fff,#e6e6e6);\n"
"  background-image: linear-gradient(to bottom,#fff,#e6e6e6);\n"
"  background-repeat: repeat-x;\n"
"  border: 1px solid #ccc;\n"
"  border-color: #e6e6e6 #e6e6e6 #bfbfbf;\n"
"  border-color: rgba(0,0,0,0.1) rgba(0,0,0,0.1) rgba(0,0,0,0.25);\n"
"  border-bottom-color: #b3b3b3;\n"
"  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffffff',endColorstr='#ffe6e6e6',GradientType=0);\n"
"  filter: progid:DXImageTransform.Microsoft.gradient(enabled=false);\n"
"  -webkit-box-shadow: inset 0 1px 0 rgba(255,255,255,0.2),0 1px 2px rgba(0,0,0,0.05);\n"
"  -moz-box-shadow: inset 0 1px 0 rgba(255,255,255,0.2),0 1px 2px rgba(0,0,0,0.05);\n"
"  box-shadow: inset 0 1px 0 rgba(255,255,255,0.2),0 1px 2px rgba(0,0,0,0.05);\n"
"}\n"
"\n"
"input[type=radio]:checked + label, input[type=checkbox]:checked + label{\n"
"  background-image: none;\n"
"  outline: 0;\n"
"  -webkit-box-shadow: inset 0 2px 4px rgba(0,0,0,0.15),0 1px 2px rgba(0,0,0,0.05);\n"
"  -moz-box-shadow: inset 0 2px 4px rgba(0,0,0,0.15),0 1px 2px rgba(0,0,0,0.05);\n"
"  box-shadow: inset 0 2px 4px rgba(0,0,0,0.15),0 1px 2px rgba(0,0,0,0.05);\n"
"  background-color:#e0e0e0;\n"
"}\n"
"#div_ipfw_port {width: 45px;}\n"
"</style>\n"
"  <style>\n"
"/* tooltipz */\n"
".tooltip {\n"
"  position: relative;\n"
"}\n"
".tooltip:hover .tooltip-inner {\n"
"  visibility: visible;\n"
"  opacity: .9;  \n"
"}\n"
".tooltip .tooltip-inner {\n"
"  position: absolute;\n"
"  display: block;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  font-weight: bold;\n"
"  left: 10px;\n"
"  padding: 4px 6px;\n"
"  max-width: 250px;\n"
"  color: #ffffff;\n"
"  background-color: #444;\n"
"  border: 2px solid #333;\n"
"  -webkit-border-radius: 4px;\n"
"          border-radius: 4px;\n"
"  visibility: hidden;\n"
"  opacity: 0;\n"
"  -webkit-transition: opacity .6s ease-in-out;\n"
"  z-index: 10;\n"
"}\n"
".tooltip.top .tooltip-inner {\n"
"  bottom: 40px;\n"
"  left: 10%;\n"
"}\n"
".tooltip.bottom .tooltip-inner {\n"
"  margin-top: 8px;\n"
"}\n"
".tooltip.blue .tooltip-inner {\n"
"  background-color: #3A87AD;\n"
"  border: 2px solid #1F6377;\n"
"}\n"
".tooltip.green .tooltip-inner {\n"
"  background-color: #468847;\n"
"  border: 2px solid #387038;\n"
"}\n"
".tooltip.orange .tooltip-inner {\n"
"  background-color: #F89406;\n"
"  border: 2px solid #AD6704;\n"
"}\n"
".tooltip.red .tooltip-inner {\n"
"  background-color: #B94A48;\n"
"  border: 2px solid #802420;\n"
"}\n"
".tooltip-angle {\n"
"  position: absolute;\n"
"  border-left-width: 0;\n"
"  line-height: 0;\n"
"  left: 20%;\n"
"}\n"
".tooltip-angle-inner {\n"
"  position: absolute;\n"
"  border-left-width: 0;\n"
"  line-height: 0;\n"
"  left: 2px;\n"
"}\n"
".tooltip.top .tooltip-angle {\n"
"  bottom: -10px;\n"
"  border-right: solid 10px transparent;\n"
"  border-top: solid 10px #333;\n"
"}\n"
".tooltip.top.blue .tooltip-angle {\n"
"  border-top: solid 10px #1F6377;\n"
"}\n"
".tooltip.top.green .tooltip-angle {\n"
"  border-top: solid 10px #387038;\n"
"}\n"
".tooltip.top.orange .tooltip-angle {\n"
"  border-top: solid 10px #AD6704;\n"
"}\n"
".tooltip.top.red .tooltip-angle {\n"
"  border-top: solid 10px #802420;\n"
"}\n"
".tooltip.top .tooltip-angle-inner {\n"
"  bottom: 5px;\n"
"  border-right: solid 5px transparent;\n"
"  border-top: solid 5px #444;\n"
"}\n"
".tooltip.top.blue .tooltip-angle-inner {\n"
"  border-top: solid 5px #3A87AD;\n"
"}\n"
".tooltip.top.green .tooltip-angle-inner {\n"
"  border-top: solid 5px #468847;\n"
"}\n"
".tooltip.top.orange .tooltip-angle-inner {\n"
"  border-top: solid 5px #F89406;\n"
"}\n"
".tooltip.top.red .tooltip-angle-inner {\n"
"  border-top: solid 5px #B94A48;\n"
"}\n"
".tooltip.bottom .tooltip-angle {\n"
"  top: -10px;\n"
"  border-right: solid 10px transparent;\n"
"  border-bottom: solid 10px #333;\n"
"}\n"
".tooltip.bottom.blue .tooltip-angle {\n"
"  border-bottom: solid 10px #1F6377;\n"
"}\n"
".tooltip.bottom.green .tooltip-angle {\n"
"  border-bottom: solid 10px #387038;\n"
"}\n"
".tooltip.bottom.orange .tooltip-angle {\n"
"  border-bottom: solid 10px #AD6704;\n"
"}\n"
".tooltip.bottom.red .tooltip-angle {\n"
"  border-bottom: solid 10px #802420;\n"
"}\n"
".tooltip.bottom .tooltip-angle-inner {\n"
"  top: 5px;\n"
"  border-right: solid 5px transparent;\n"
"  border-bottom: solid 5px #444;\n"
"}\n"
".tooltip.bottom.blue .tooltip-angle-inner {\n"
"  border-bottom: solid 5px #3A87AD;\n"
"}\n"
".tooltip.bottom.green .tooltip-angle-inner {\n"
"  border-bottom: solid 5px #468847;\n"
"}\n"
".tooltip.bottom.orange .tooltip-angle-inner {\n"
"  border-bottom: solid 5px #F89406;\n"
"}\n"
".tooltip.bottom.red .tooltip-angle-inner {\n"
"  border-bottom: solid 5px #B94A48;\n"
"}\n"
".tooltip.tip .tooltip-angle {\n"
"  left: 10px;\n"
"}\n"
"  </style>\n"
"<script>\n"
"function c(l)\n"
"{document.getElementById('s').value=l.innerText||l.textContent;document.getElementById('p').focus();}\n"
"</script>\n"
"<script>\n"
"if (window.location.search.substr(1) != '')\n"
"{\n"
"document.getElementById('config').display = 'none';\n"
"document.body.innerHTML ='<h1>μ-Trident8266 Router Config</h1>The new settings have been sent to the device...';\n"
"setTimeout(\"location.href = '/'\",10000);\n"
"}\n"
"\n"
"</script>\n"
"</head>\n"
"<body>\n"
"<em>μ-Trident8266</em>\n"
"<div style='font-weight: bold;font-size:140%;'>micro-router for IoT</div>\n"
"<div id='config' style='text-align:left;display:inline-block;min-width:260px;'>\n"
"<br>\n"
"\n"
"\n"
"<script type='text/javascript'>\n"
"function ip_config_func(display){\n"
"  if(display){\n"
"    document.getElementById('ip_config2').style.display = 'none';\n"
"    document.getElementById('ip_config1').style.display = '';\n"
"    document.getElementById('ip').disabled = true;\n"
"    document.getElementById('gw').disabled = true;\n"
"    document.getElementById('netmask').disabled = true;\n"
"  }else{\n"
"    document.getElementById('ip_config2').style.display = '';\n"
"    document.getElementById('ip_config1').style.display = 'none';\n"
"    document.getElementById('ip').disabled = false;\n"
"    document.getElementById('gw').disabled = false;\n"
"    document.getElementById('netmask').disabled = false;\n"
"  }\n"
"}\n"
"</script>\n"
"<div id=groupbar>WiFi&nbsp;&nbsp;&nbsp;MQTT&nbsp;&nbsp;&nbsp;\n"
"System&nbsp;&nbsp;&nbsp;SmartFarm</div><br>\n";

String page_html_wifi_part1 = 
"<div class=group>\n"
"<div id=groupsetting>WiFi</div>\n"
"<div id=subsetting>STA Settings</div>\n"
"<form action='' method='GET'>\n"
"<table>\n"
"  <tr>\n"
"  <td class=td_form>SSID:</td>\n"
"  <td>\n"
"<div class='tooltip top blue'>\n"
"<input type='text' name='ssid' value='%s_ssid'/>\n"
"<div class='tooltip-inner'>ชื่อ WiFi ที่ต้องการเชื่อมต่อ</div>\n"
"</div>\n"
"</td>\n"
"  </tr>\n"
"  <tr>\n"
"  <td>Password:</td>\n"
"  <td>\n"
"<div class='tooltip top blue'>\n"
"<input type='text' name='ap_password' value='%s_password'/>\n"
"<div class='tooltip-inner'>Password ความยาวขั้นต่ำ 8 อักขระ</div>\n"
"</div>\n"
"  </td>\n"
"  </tr>\n"
"  <tr>\n"
"  <td><b>Option</b></td>\n"
"  <td></td>\n"
"  </tr>\n"
"  <tr>\n"
"  <td>BBSID:</td>\n"
"  <td>\n"
"<div class='tooltip top blue'>\n"
"<input type='text' name='bbsid' value='%s_bssid'/>\n"
"<div class='tooltip-inner'>MAC Address ของอุปกรณ์ไวไฟที่จะเชื่อมต่อ <br><br><small>(กรณี WiFi มีชื่อซ้ำกันหลายชุด)</small></div>\n"
"</div>\n"
"  </td>\n"
"  </tr>\n"
"  <tr>\n"
"  <td>DNS:</td>\n"
"  <td>\n"
"<div class='tooltip top blue'>\n"
"<input type='text' name='dns' value='%s_dns'/>\n"
"<div class='tooltip-inner'>Domain Name Server</div>\n"
"</div>\n"
"  </td>\n"
"  <tr>\n"
"  <td id=tdsmall colspan=2></td>\n"
"  </tr>\n"
"  <tr>\n"
"  <td><b>IP Address</b></td>\n"
"  <td>&nbsp;\n"
"    <input type='radio' class='radio_display_none' id='radio1' name='ip_type' value='dhcp' checked>\n"
"       <label for='radio1' onclick='ip_config_func(true)'>อัตโนมัติ</label>&nbsp;&nbsp;\n"
"    <input type='radio' class='radio_display_none' id='radio2' name='ip_type' value='non_dhcp'>\n"
"       <label for='radio2' onclick='ip_config_func(false)'>กำหนดเอง</label>\n"
"  </td>\n"
"  </tr>\n"
"  <tr id=ip_config1>\n"
"  <td>STA IP:</td>\n"
"  <td>\n"
"<div class='tooltip top blue'>\n"
"%s_my_ip\n"
"<div class='tooltip-inner'>IP Address เมื่อเชื่อมต่อในโหมด STATION</div>\n"
"</div>\n"
"  </td>\n"
"  </tr>\n"
"  <tr   id=ip_config2  style='display: none;'>\n"
"  <td colspan=2>\n"
"  <table>\n"
"  <tr>\n"
"  <td  class=td_form>STA IP:</td>\n"
"  <td>\n"
"<div class='tooltip top blue'>\n"
"<input type='text' id='ip' name='ip' value='%s_my_addr'/>\n"
"<div class='tooltip-inner'>IP Address เมื่อเชื่อมต่อในโหมด STATION</div>\n"
"</div>\n"
"  </td>\n"
"  </tr>\n"
"  <tr>\n"
"  <td>Gateway IP:</td>\n"
"  <td>\n"
"<div class='tooltip top blue'>\n"
"<input type='text' id='gw' name='gw' value='%s_my_gw'/>\n"
"<div class='tooltip-inner'>IP Address ของ Gateway</div>\n"
"</div>\n"
"  </td>\n"
"  </tr>\n"
"  <tr>\n"
"  <td>NetMask:</td>\n"
"  <td>\n"
"<div class='tooltip top blue'>\n"
"<input type='text' id='netmask' name='netmask' value='%s_my_netmask'/>\n"
"<div class='tooltip-inner'>Netmask สำหรับการเชื่อมต่อ WiFi</div>\n"
"</div>\n"
"  </td>\n"
"  </tr>\n"
"  </table>\n"
"  </td>\n"
"  </tr>\n"
"  <tr>\n"
"  <td>STA MAC:</td>\n"
"  <td>\n"
"<div class='tooltip top blue'>\n"
"%s_sta_mac\n"
"<div class='tooltip-inner'>MAC Address เมื่อเชื่อมต่อในโหมด STATION</div>\n"
"</div>\n"
"  </td>\n"
"  <tr>  <td id=tdsmall colspan=2></td>\n"
"  </tr>\n"
"  <tr>\n"
"  <td colspan=2><button type='submit'/>Connect</button></td>\n"
"  </tr>\n"
"</table>\n"
"</form>\n"
"\n";

String page_html_wifi_part2 = 
"<div id=subsetting>AP Settings</div>\n"
"<form action='' method='GET'>\n"
"<table>\n"
"  <tr>\n"
"  <td class=td_form>SSID:</td>\n"
"  <td>\n"
"<div class='tooltip top blue'>\n"
"<input type='text' name='ap_ssid' value='%s_ap_ssid'/>\n"
"<div class='tooltip-inner'>ชื่อ AccessPoint ที่จะปล่อยสัญญาณไวไฟ</div>\n"
"</div>\n"
"  </td>\n"
"  </tr>\n"
"  <tr>\n"
"  <td>Password:</td>\n"
"  <td>\n"
"<div class='tooltip top blue'>\n"
"<input type='text' name='ap_password' value='%s_ap_password'/>\n"
"<div class='tooltip-inner'>Password ความยาวขั้นต่ำ 8 อักขระ</div>\n"
"</div>\n"
"  </td>\n"
"  </tr>\n"
"  <tr>\n"
"  <td>Security:</td>\n"
"  <td>\n"
"<div class='tooltip top blue'>\n"
"   <select name='ap_open'>\n"
"   <option value='open' %s_ap_open>Open</option>\n"
"   <option value='wpa2' %s_ap_wpa2>WPA2</option>\n"
"  </select>\n"
"<div class='tooltip-inner'>มาตรฐานความปลอดภัย</div>\n"
"</div>\n"
"  </td>\n"
"  </tr>\n"
"  <tr>\n"
"  <td>AP IP:</td>\n"
"  <td>\n"
"<div class='tooltip top blue'>\n"
"%s_network_addr\n"
"<div class='tooltip-inner'>IP Address เมื่อเชื่อมต่อในโหมด AcccessPoint</div>\n"
"</div>\n"
"  </td>\n"
"  </tr>\n"
"  <tr>\n"
"  <td>AP MAC:</td>\n"
"  <td>\n"
"<div class='tooltip top blue'>\n"
"%s_ap_mac\n"
"<div class='tooltip-inner'>MAC Address เมื่อเชื่อมต่อในโหมด AcccessPoint <br><br><small>(นำใช้ใน BBSID สำหรับลูกข่ายต้องการเชื่อมต่อแบบเจาะจง)</small></div>\n"
"</div>\n"
"  </td>\n"
"  <tr>\n"
"  <tr>\n"
"  <td>AP Hidden:</td>\n"
"  <td>\n"
"<div class='tooltip top blue'>\n"
"<div style='width:20pt;'>\n"
"<input id=ap_unhidden type='hidden' name='ap_hidden' value='0'>\n"
"<input id=ap_hidden type='checkbox' name='ap_hidden' value='1' onclick=\"document.getElementById('ap_unhidden').disabled = document.getElementById('ap_hidden').checked;\">\n"
"</div>\n"
"<div class='tooltip-inner'>ติ๊กเครื่องหมายถูก เพื่อซ่อน AccessPoint<br><br><small>(ป้องกันบุคคลภายนอกมองเห็น)</small></div>\n"
"</div>\n"
"  </td>\n"
"  </tr>\n"
"  <tr>\n"
"  <td class=tdsmall colspan=2></td>\n"
"  </tr>\n"
"  <tr>\n"
"  <td colspan=2><button type='submit'/>Set</button></td>\n"
"  </tr>\n"
"</table>\n"
"</form>\n"
"</div>\n";


//const char page_html_part3[] PROGMEM = 
//"<div class=group>\n"
//"<div id=groupsetting>MQTT</div>\n"
//"<form action='' method='GET'>\n"
//"<table>\n"
//"  <tr>\n"
//"  <td class=td_form>MQTT Broker:</td>\n"
//"  <td><input type='text' name='mqtt_host' value='%s'/></td>\n"
//"  </tr>\n"
//"  <tr>\n"
//"  <td>MQTT Port:</td>\n"
//"  <td><input type='text' name='mqtt_port' value='%s'/></td>\n"
//"  </tr>\n"
//"  <tr>\n"
//"  <td>MQTT User:</td>\n"
//"  <td><input type='text' name='mqtt_user' value='%s'/></td>\n"
//"  </tr>\n"
//"  <td>MQTT Pass:</td>\n"
//"  <td><input type='text' name='mqtt_password' value='%s'/></td>\n"
//"  </tr>\n"
//"  <tr>\n"
//"  <td class=tdsmall colspan=2>&nbsp;</td>\n"
//"  </tr>\n"
//"  <tr>\n"
//"  <td colspan=2><button type='submit'/>Connect</button></td>\n"
//"  </tr>\n"
//"</table>\n"
//"</form>\n"
//"\n"
//"<div id=subsetting>Publish Topic</div>\n"
//"<form action='' method='GET'>\n"
//"<table>\n"
//"  <tr>\n"
//"  <td>Topic:</td>\n"
//"  <td><input type='text' name='mqtt_host' value='%s'/></td>\n"
//"  </tr>\n"
//"  <tr>\n"
//"  <td class=tdsmall colspan=2>&nbsp;</td>\n"
//"  </tr>\n"
//"  <tr>\n"
//"  <td colspan=2><button type='submit'/>Set</button></td>\n"
//"  </tr>\n"
//"</table>\n"
//"</form>\n"
//"</div>\n";
//
//
//const char page_html_part4[] PROGMEM = 
//"<div class=group>\n"
//"<div id=groupsetting>System</div>\n"
//"<form action='' method='GET'>\n"
//"<table>\n"
//"  <tr>\n"
//"  <td class=td_form>Clock Speed:</td>\n"
//"  <td>\n"
//"    <input type='radio'  class='radio_display_none' id='speed1' name='speed' value='80' checked>\n"
//"       <label for='speed1'>80MHz</label>&nbsp;&nbsp;&nbsp;&nbsp;\n"
//"    <input type='radio' class='radio_display_none'  id='speed2' name='speed' value='160'>\n"
//"       <label for='speed2'>160MHz</label>\n"
//"  </td>\n"
//"  </tr>\n"
//"  <tr>\n"
//"  <td>NTP Server:</td>\n"
//"  <td><input type='text' name='npt_host' value='%s'/></td>\n"
//"  </tr>\n"
//"  <td>TimeZone:</td>\n"
//"  <td><input type='text' name='npt_timezone' value='%s'/></td>\n"
//"  </tr>\n"
//"  <tr>\n"
//"  <td class=tdsmall colspan=2>&nbsp;</td>\n"
//"  </tr>\n"
//"  <tr>\n"
//"  <td colspan=2><button type='submit'/>Set</button></td>\n"
//"  </tr>\n"
//"</table>\n"
//"</form>\n"
//"</div>\n";
//
//
//const char page_html_part5[] PROGMEM = 
//"<script type='text/javascript'>\n"
//"function setPort(){\n"
//"  var selectObject = document.getElementById('ipfw_proto');\n"
//"  var proto  = selectObject.options[selectObject.selectedIndex].value;\n"
//"\n"
//"  var portObject = document.getElementById('ipfw_int_port');\n"
//"\n"
//"  switch(proto){\n"
//"    case 'http':\n"
//"      portObject.value  = 80;\n"
//"      break;\n"
//"    case 'mqtt':\n"
//"      portObject.value  = 1883;\n"
//"      break;\n"
//"    case 'ftp':\n"
//"      portObject.value  = 21;\n"
//"      break;\n"
//"    case 'ssh':\n"
//"      portObject.value  = 22;\n"
//"      break;\n"
//"    case 'telnet':\n"
//"      portObject.value  = 23;\n"
//"      break;\n"
//"    case 'smtp':\n"
//"      portObject.value  = 25;\n"
//"      break;\n"
//"    case 'pop':\n"
//"      portObject.value  = 110;\n"
//"      break;\n"
//"    case 'imap':\n"
//"      portObject.value  = 143;\n"
//"      break;\n"
//"    case 'dns':\n"
//"      portObject.value  = 53;\n"
//"      break;\n"
//"    case 'dhcp':\n"
//"      portObject.value  = 67;\n"
//"      break;\n"
//"    case 'ntp':\n"
//"      portObject.value  = 123;\n"
//"      break;\n"
//"    case 'rtp':\n"
//"      portObject.value  = '';\n"
//"      break;\n"
//"    case 'rtsp':\n"
//"      portObject.value  = 554;\n"
//"      break;\n"
//"    case 'voip':\n"
//"      portObject.value  = '';\n"
//"      break;\n"
//"    default:\n"
//"      portObject.value  = '';\n"
//"      break;\n"
//"  }\n"
//"}\n"
//"</script>\n"
//"\n"
//"<div class=group>\n"
//"<div id=groupsetting>IP-Forward</div>\n"
//"<form action='' method='GET'>\n"
//"<input type='hidden' name='ipfw_cmd' value='add'>\n"
//"<table cellspacing=0 border=0>\n"
//"  <tr align='center'  style='font-weight: bold;'>\n"
//"  <td class=tdzero>ประเภท</td>\n"
//"  <td class=tdzero><div style='color: #7F0000;' class=divzero><small>[Port&nbsp;ภายนอก]</small></div></td>\n"
//"  <td>&nbsp;&#x2192;&nbsp;</td>\n"
//"  <td colspan=3 class=tdzero><div style='color: #00137F' class=divzero><small>[IP&nbsp;:&nbsp;Port&nbsp;ภายใน]</small></div></td>\n"
//"  </tr>\n"
//"  <tr align='center' style='font-weight: bold;'>\n"
//"  <td class=tdzero>\n"
//"<div class='tooltip top blue'>\n"
//"<select name='ipfw_proto' id='ipfw_proto' onchange='setPort()' style='width: 50px; height: 30px; font-size: 10px;'>\n"
//" <option value='tcp'%s>TCP</option>\n"
//" <option value='udp'%s>UDP</option>\n"
//" <option value='http'%s>HTTP</option>\n"
//" <option value='mqtt'%s>MQTT</option>\n"
//" <option value='ftp'%s>FTP</option>\n"
//" <option value='ssh'%s>SSH</option>\n"
//" <option value='telnet'%s>TELNET</option>\n"
//" <option value='smtp'%s>SMTP</option>\n"
//" <option value='pop'%s>POP</option>\n"
//" <option value='imap'%s>IMAP</option>\n"
//" <option value='dns'%s>DNS</option>\n"
//" <option value='dhcp'%s>DHCP</option>\n"
//" <option value='ntp'%s>NTP</option>\n"
//" <option value='rtp'%s>RTP</option>\n"
//" <option value='rtsp'%s>RTSP</option>\n"
//" <option value='voip'%s>VoIP</option>\n"
//"</select>\n"
//"<div class='tooltip-inner'>โปรโตคอล</div>\n"
//"  </td>\n"
//"  <td style='width: 60px;' class=tdzero>\n"
//"  <div class='tooltip top blue'>\n"
//"  <div id=div_ipfw_port class=divzero><input type='text' name='ipfw_ext_port' value='' style='height: 30px; font-size: 10px;'/></div>\n"
//"  <div class='tooltip-inner'>Port&nbsp;ภายนอก</div>\n"
//"  </td>\n"
//"\n"
//"  <td class=tdzero>&#x2192;</td>\n"
//"  <td class=tdzero>\n"
//"  <div class='tooltip top blue'>\n"
//"<select name='ipfw_int_ip' style='height: 30px; font-size: 12px;'>\n"
//" <option value='2'%s>10.0.0.2</option>\n"
//" <option value='3'%s>10.0.0.3</option>\n"
//" <option value='4'%s>10.0.0.4</option>\n"
//" <option value='5'%s>10.0.0.5</option>\n"
//" <option value='6'%s>10.0.0.6</option>\n"
//" <option value='7'%s>10.0.0.7</option>\n"
//" <option value='8'%s>10.0.0.8</option>\n"
//"</select>\n"
//"<div class='tooltip-inner'>IP:Port&nbsp;ภายใน</div>\n"
//"  </td>\n"
//"  <td class=tdzero>:</td>\n"
//"  <td style='width: 60px;'  class=tdzero>\n"
//"\n"
//"  <div id=div_ipfw_port class=divzero><input type='text' name='ipfw_int_port' id='ipfw_int_port' value='' style='height: 30px;font-size: 10px;'/></div>\n"
//"\n"
//"  </td>\n"
//"  </tr>\n"
//"  <tr>\n"
//"  <td colspan=6><button type='submit'/>Add IP-Forward</button></td>\n"
//"  </tr>\n"
//"</table>\n"
//"</form>\n"
//"<script type='text/javascript'>\n"
//"function ipfw_remove_tcp(){\n"
//"  document.getElementById('ipfw_remove_button').disabled = false; \n"
//"  document.getElementById('tcp_type').disabled = false; \n"
//"  document.getElementById('udp_type').disabled = true;\n"
//"}\n"
//"function ipfw_remove_udp(){\n"
//"  document.getElementById('ipfw_remove_button').disabled = false; \n"
//"  document.getElementById('tcp_type').disabled = true; \n"
//"  document.getElementById('udp_type').disabled = false;\n"
//"}\n"
//"</script>\n"
//"<form action='' method='GET'>\n"
//"<input type='hidden' name='ipfw_cmd' value='remove'>\n"
//"<input id='tcp_type' type='hidden' name='ipfw_type' value='tcp' disabled>\n"
//"<input id='udp_type' type='hidden' name='ipfw_type' value='udp' disabled>\n"
//"<table>\n"
//"  <tr align='left'>\n"
//"  <th colspan=2>TCP</th>\n"
//"  </tr>\n"
//"  <tr align='left' style='font-weight: bold; font-size:14px;'>\n"
//"  <td width='30px'><input type='radio' name='ipfw_ext_port' value='5023' onclick='ipfw_remove_tcp();'></td>\n"
//"  <td>http</td>\n"
//"  <td><div style='color: #7F0000'>[2080]</div></td><td>&#x2192;</td><td><div style='color: #00137F'>[10.0.0.5:80]</div></td>\n"
//"  </tr>\n"
//"  <tr align='left' style='font-weight: bold; font-size:14px;'>\n"
//"  <td width='30px'><input type='radio' name='ipfw_ext_port' value='5023' onclick='ipfw_remove_tcp();'></td>\n"
//"  <td>ftp</td>\n"
//"  <td><div style='color: #7F0000'>[5021]</div></td><td>&#x2192;</td><td><div style='color: #00137F'>[10.0.0.5:21]</div></td>\n"
//"  </tr>\n"
//"  <tr align='left' style='font-weight: bold; font-size:14px;'>\n"
//"  <td width='30px'><input type='radio' name='ipfw_ext_port' value='5023' onclick='ipfw_remove_tcp();'></td>\n"
//"  <td>telnet</td>\n"
//"  <td><div style='color: #7F0000'>[5023]</div></td><td>&#x2192;</td><td><div style='color: #00137F'>[10.0.0.5:23]</div></td>\n"
//"  </tr>\n"
//"  <tr align='left' style='font-weight: bold; font-size:14px;'>\n"
//"  <td width='30px'><input type='radio' name='ipfw_ext_port' value='6025' onclick='ipfw_remove_tcp();'></td>\n"
//"  <td>smtp</td>\n"
//"  <td><div style='color: #7F0000'>[6025]</div></td><td>&#x2192;</td><td><div style='color: #00137F'>[10.0.0.6:25]</div></td>\n"
//"  </tr>\n"
//"  <tr align='left' style='font-weight: bold; font-size:14px;'>\n"
//"  <td width='30px'><input type='radio' name='ipfw_ext_port' value='7883' onclick='ipfw_remove_tcp();'></td>\n"
//"  <td>mqtt</td>\n"
//"  <td><div style='color: #7F0000'>[7883]</div></td><td>&#x2192;</td><td><div style='color: #00137F'>[10.0.0.7:1883]</div></td>\n"
//"  </tr>\n"
//"  <tr align='left' style='font-weight: bold; font-size:14px;'>\n"
//"  <td width='30px'><input type='radio' name='ipfw_ext_port' value='6554' onclick='ipfw_remove_tcp();'></td>\n"
//"  <td>rtsp</td>\n"
//"  <td><div style='color: #7F0000'>[6554]</div></td><td>&#x2192;</td><td><div style='color: #00137F'>[10.0.0.6:554]</div></td>\n"
//"  </tr>\n"
//"\n"
//"  <tr align='left'>\n"
//"  <th colspan=2>UDP</th>\n"
//"  </tr>\n"
//"  <tr align='left' style='font-weight: bold; font-size:14px;'>\n"
//"  <td width='30px'><input type='radio' name='ipfw_ext_port' value='5023' onclick='ipfw_remove_udp();'></td>\n"
//"  <td>udp</td>\n"
//"  <td><div style='color: #7F0000'>[5011]</div></td><td>&#x2192;</td><td><div style='color: #00137F'>[10.0.0.5:11]</div></td>\n"
//"  </tr>\n"
//"  <tr align='left' style='font-weight: bold; font-size:14px;'>\n"
//"  <td width='30px'><input type='radio' name='ipfw_ext_port' value='5023' onclick='ipfw_remove_udp();'></td>\n"
//"  <td>ntp</td>\n"
//"  <td><div style='color: #7F0000'>[5123]</div></td><td>&#x2192;</td><td><div style='color: #00137F'>[10.0.0.5:123]</div></td>\n"
//"  </tr>\n"
//"  <tr>\n"
//"  <td colspan=5><button id=ipfw_remove_button type='submit' disabled/>Remove IP-Forward</button></td>\n"
//"  </tr>\n"
//"</table>\n"
//"</form>\n"
//"</div>\n";

String page_html_end = 
"<br><br>\n"
"<table>\n"
"<tr>\n"
"<td><form action='' method='GET'><button type='submit'/>WiFi reset</button></form></td>\n"
"<td><form action='' method='GET'><button type='submit'  name='dolock' />Lock</button></form></td>\n"
"<td><form action='' method='GET'><button type='submit'/>Restart</button></form></td>\n"
"</tr>\n"
"</table>\n"
"\n"
"</body>\n"
"</html>\n";

